from .settings import (
    FREEPIK_BASE_URL, OPENART_BASE_URL, PIXLR_BASE_URL,
    COLLECTED_DIR,DATASET_DIR,
    CONSIDER_MAX_ITERATON, MAX_ITERATON, PIXLR_MAX_ITERATON,
    DOWNLOAD_BATCH, EPOCH,
    TRY_MANY, WATING,
    SEARCH_PROMPTS, PLATFORMS
)