name: Create Dataset

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run creation script
        env:
          EPOCH: ${{ vars.EPOCH }}
          DOWNLOAD_BATCH: ${{ vars.DOWNLOAD_BATCH }}
        run: python generate_dataset.py

      - name: Commit and push changes with retry
        run: |
          for i in {1..3}; do
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions@github.com"
            git add -f dataset
            git add -f collected
            git commit -m "downlaoad images: $(date)" || echo "No changes to commit"
            git pull --rebase origin ${{ github.ref_name }}
            git push && break || echo "Push failed, retrying in 5 seconds... ($i/3)"
            sleep 5
          done
          if [ $i -eq 3 ]; then
            echo "Push failed after 3 attempts."
            exit 1
          fi
