name: Scrap images

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [""] # ["pixlr", "openart", "freepik"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collection
        env:
          CONSIDER_MAX_ITERATON: ${{ vars.CONSIDER_MAX_ITERATON }}
          MAX_ITERATON: ${{ vars.MAX_ITERATON }}
          PIXLR_MAX_ITERATON: ${{ vars.PIXLR_MAX_ITERATON }}
          WATING: ${{ vars.WATING }}
          TRY_MANY: ${{ vars.TRY_MANY }}
          SEARCH_PROMPTS: ${{ vars.SEARCH_PROMPTS }}
          PLATFORMS: ${{ matrix.platform }}
        run: python main.py

      - name: Commit and push changes with retry
        run: |
          for i in {1..3}; do
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions@github.com"
            git add -f collected
            git commit -m "Collected and updated data for ${{ matrix.platform }}: $(date)" || echo "No changes to commit"
            git pull --rebase origin ${{ github.ref_name }}
            git push && break || echo "Push failed, retrying in 5 seconds... ($i/3)"
            sleep 5
          done
          if [ $i -eq 3 ]; then
            echo "Push failed after 3 attempts."
            exit 1
          fi

